name: Push Check

on: push

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install #Install node_modules
      - run: npm run build
      - run: npm run prettier:check
        if: always()
      # - run: yarn test
